### ISSUE TITLE
"download" can run out of memory

### ISSUE THREAD

**Issue by Redundancy** [AstinCHOI/netstorage-python#1]
Even though it's downloading to a local file, the download command can run out of memory.
I assume that it's trying to read the entire payload into memory rather than streaming it.

**Comment by Redundancy** [comment]
http://stackoverflow.com/questions/16694907/how-to-download-large-file-in-python-with-requests-py
would probably fix this.

**Comment by AstinCHOI** [comment]
Hi @Redundancy,
Thanks for issuing the problem !
I fix it as the stackoverflow link you provide.

$ pip install --upgrade netstorageapi

If there have any problems after fixing it, please reissue.
Thanks !
