### ISSUE TITLE
zip-indexing not working

### ISSUE THREAD

**Issue by hitechvivek** [AstinCHOI/netstorage-python#16]
Index-zip=2 is not yet supported, It needs to be reverted back to index-zip=1 (Line 210-212)

https://learn.akamai.com/en-us/webhelp/netstorage/netstorage-user-guide/GUID-1D866F9E-FD8D-46C2-81B4-AAB06215063A.html

**Comment by ahendley** [comment]
Experiencing the same behaviour.

**Comment by shabadoo75** [comment]
me too, would be great to get that PR merged

**Comment by akalcosmin** [comment]
PR merged, issue fixed.
