### ISSUE TITLE
Need ability add optional action header fields

### ISSUE THREAD

**Issue by dineshdh** [AstinCHOI/netstorage-python#2]
In particular I want to use the “serve-from-zip” feature. In order to do this I need to append **index-zip=1** to the end of the action header

It would be great if you could add this to the Python module. Preferably in a very generic implementation to cater for any other such requirements by other users.

**Comment by AstinCHOI** [comment]
@dineshdh Okay, I will add soon !

**Comment by dineshdh** [comment]
Fantastic. Thank you, much appreciated

**Comment by AstinCHOI** [comment]
Hi, @dineshdh 

Update done !

1) update your package
$ pip install --upgrade netstorageapi

2) Use INDEX_ZIP
upload(local_source, ns_target, True)
please be aware that INDEX_ZIP supports only for FileStore

Thanks !
