### ISSUE TITLE
INDEX_ZIP not working

### ISSUE THREAD

**Issue by dineshdh** [AstinCHOI/netstorage-python#3]
This seems to no longer work. Not sure whats happened.

Just to confirm I modified the upload test to include the additional optional param INDEX_ZIP value of True and the test fails. Can you please have a look and also include an additional upload test which includes INDEX_ZIP.

**Comment by dineshdh** [comment]
this is the response.text . Weird
```
<!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">
<HTML><HEAD>
<TITLE>400 Bad Request</TITLE>
</HEAD><BODY>
<H1>Bad Request</H1>
Your browser sent a request that this server could not understand.<P>
(mod_postfile) az2z failed: [2]<P>
</BODY></HTML>
```

**Comment by AstinCHOI** [comment]
Hi @dineshdh 

Are you using Filestore? 
and did you configure "Enable az2z zip uploads" in FileStore setting?
(If you don't know about this, you can send the email to your akamai representative or issue a ticket to control.akamai.com)

**Comment by dineshdh** [comment]
Hi @AstinCHOI 

Yes az2z zip uploads is enabled

**Comment by AstinCHOI** [comment]
Okay, I checked 200 okay!
Could you attach your code except your netstorage private key?

**Comment by AstinCHOI** [comment]
I got your problem. You should upload .zip file !
