### ISSUE TITLE
Authentication Params

### ISSUE THREAD

**Issue by jrdiniz** [AstinCHOI/netstorage-python#7]
Hi,

I can't find the params:

NS_KEYNAME = ''
NS_KEY = '' 

On Luna API web interface, a tried with success use the EdgeGridAtuh, using the params client_token, client_secret and access_token, what of this params I need to use to do in netstorage.

When I try to use of the keys I receve the error

{
  "type": "https://problems./-/pep-authn/request-error",
  "title": "Bad request",
  "status": 400,
  "detail": "Authorization header missing",
  "instance": "https://akab-dirhh6ii5kh2ifii-zbvcq77dufavmtay.luna.akamaiapis.net/xxxx/requeriments.txt",
  "method": "PUT",
  "serverIp": "23.44.188.85",
  "clientIp": "200.192.194.2",
  "requestId": "16a030b8",
  "requestTime": "2018-01-17T18:44:07Z"
}

**Comment by AstinCHOI** [comment]
Hi @jrdiniz,
There is the netstorage key params, not (client_token, client_secret and access_token).
You can see the netstorage credential in your netstorage account info.

If you didn't turn using Netstorage API on, first you have to turn it on.
